services:
  postgres:
    image: 'postgres:16.1'
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Pokemon
    volumes:
      - ./db-data/:/var/lib/postgresql/data/